server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver

image:
  url: https://vk.com/tortarmavir_kochetkova_kris?z=photo

